// flow-typed signature: b00b3c37872f39b009131281a503f792
// flow-typed version: <<STUB>>/@nivo/bar_v0.61.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/bar/dist/nivo-bar.cjs' {
  declare module.exports: any;
}

declare module '@nivo/bar/dist/nivo-bar.esm' {
  declare module.exports: any;
}

declare module '@nivo/bar/dist/nivo-bar.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/bar/dist/nivo-bar.cjs.js' {
  declare module.exports: $Exports<'@nivo/bar/dist/nivo-bar.cjs'>;
}
declare module '@nivo/bar/dist/nivo-bar.esm.js' {
  declare module.exports: $Exports<'@nivo/bar/dist/nivo-bar.esm'>;
}
declare module '@nivo/bar/dist/nivo-bar.umd.js' {
  declare module.exports: $Exports<'@nivo/bar/dist/nivo-bar.umd'>;
}
