// flow-typed signature: 63ad9786d164334a4656cfb78b13efbf
// flow-typed version: <<STUB>>/@nivo/line_v0.61.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/line'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/line' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/line/dist/nivo-line.cjs' {
  declare module.exports: any;
}

declare module '@nivo/line/dist/nivo-line.esm' {
  declare module.exports: any;
}

declare module '@nivo/line/dist/nivo-line.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/line/dist/nivo-line.cjs.js' {
  declare module.exports: $Exports<'@nivo/line/dist/nivo-line.cjs'>;
}
declare module '@nivo/line/dist/nivo-line.esm.js' {
  declare module.exports: $Exports<'@nivo/line/dist/nivo-line.esm'>;
}
declare module '@nivo/line/dist/nivo-line.umd.js' {
  declare module.exports: $Exports<'@nivo/line/dist/nivo-line.umd'>;
}
