// flow-typed signature: 003fe06d49d3d0c87d5dab30a881fd24
// flow-typed version: <<STUB>>/@nivo/pie_v0.61.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/pie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/pie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/pie/dist/nivo-pie.cjs' {
  declare module.exports: any;
}

declare module '@nivo/pie/dist/nivo-pie.esm' {
  declare module.exports: any;
}

declare module '@nivo/pie/dist/nivo-pie.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/pie/dist/nivo-pie.cjs.js' {
  declare module.exports: $Exports<'@nivo/pie/dist/nivo-pie.cjs'>;
}
declare module '@nivo/pie/dist/nivo-pie.esm.js' {
  declare module.exports: $Exports<'@nivo/pie/dist/nivo-pie.esm'>;
}
declare module '@nivo/pie/dist/nivo-pie.umd.js' {
  declare module.exports: $Exports<'@nivo/pie/dist/nivo-pie.umd'>;
}
