// flow-typed signature: 771cee0c6feb7e7481770803c5ed61ae
// flow-typed version: <<STUB>>/@nivo/scatterplot_v0.61.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/scatterplot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/scatterplot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/scatterplot/dist/nivo-scatterplot.cjs' {
  declare module.exports: any;
}

declare module '@nivo/scatterplot/dist/nivo-scatterplot.esm' {
  declare module.exports: any;
}

declare module '@nivo/scatterplot/dist/nivo-scatterplot.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/scatterplot/dist/nivo-scatterplot.cjs.js' {
  declare module.exports: $Exports<'@nivo/scatterplot/dist/nivo-scatterplot.cjs'>;
}
declare module '@nivo/scatterplot/dist/nivo-scatterplot.esm.js' {
  declare module.exports: $Exports<'@nivo/scatterplot/dist/nivo-scatterplot.esm'>;
}
declare module '@nivo/scatterplot/dist/nivo-scatterplot.umd.js' {
  declare module.exports: $Exports<'@nivo/scatterplot/dist/nivo-scatterplot.umd'>;
}
